### PR TITLE
Make it work with multiple sites

### PR DESCRIPTION
**Pull request by oligot**
This was merged in #12 but removed in commit
5f77835ff27cfc836bada2bfe999876b76ff43fb

This commit reintroduce the change needed to make it work

### CODE REVIEW

**Comment by capaj** [comment]
@oligot sorry, this one slipped through the cracks

**Comment by peteruithoven** [comment]
@oligot Bold question; maybe you could add a unit test, so this doesn't happen again?

**Comment by capaj** [comment]
@peteruithoven I was just looking at it. I need to mock Socket.io and System.js-maybe tomorrow evening.

**Comment by peteruithoven** [comment]
Then you might find the following experiment interesting:
https://github.com/peteruithoven/mocking

**Pull request merged**
