### PR TITLE
Added support for next version of systemjs-hmr

### PR DESCRIPTION
**Pull request by alexisvincent**

### CODE REVIEW

**Comment by alexisvincent** [comment]
@capaj Ok to merge?

**Comment by jjrv** [comment]
Maybe better remove `yarn.lock`? It's pretty big.

**Comment by alexisvincent** [comment]
@capaj Is it ok if I move forward and merge further pull requests myself?

**Comment by capaj** [comment]
@alexisvincent yarn.lock is good for apps, this is a library/utility we want to get patches from upstream dependencies. Good thing you removed it. Seems ok to merge.

**Comment by alexisvincent** [comment]
Technically, the yarn lock only applies to server side code. In this case, the build system. So I would argue that a yarn lock is good. But its out :)

**Pull request merged**
