### PR TITLE
Switch to systemjs-hmr

### PR DESCRIPTION
**Pull request by alexisvincent**

### CODE REVIEW

**Comment by alexisvincent** [comment]
@capaj Can you review this please

**Comment by peteruithoven** [comment]
What kind of impact will this have on people using the systemjs-hot-reloader? Will this break the API? Will the __reload and __unload hooks still work? 
I really like the fact that this turns most of the logic into general SystemJS hooks. Turning this library into simply a connector to a SocketIO server.

**Comment by alexisvincent** [comment]
@peteruithuvon, yeah, so the only impact this will have is if people are using the events that systems-hot-reloader is emitting. 
Currently it emits the following events: change, deleted, moduleRecordNotFound, allReimported and error. The ones going away will be: moduleRecordNotFound, allReimported.
If you use either of these, please let me know and we can try work around this. 

But I think mostly people aren't using these events.

**Comment by born2net** [comment]
As far as I know the underlying API will not change. 
right? all remains as is as far as the interface?

**Comment by alexisvincent** [comment]
Other then that the API won't change for now. In the future we will be revisiting the best way to handle unload and reload events. See my thoughts 
here https://github.com/alexisvincent/systemjs-hmr#loader-plugin-unload-hook 
and here https://github.com/alexisvincent/systemjs-hmr#state-hydration-and-the-loader-plugin-reload-hook

**Pull request merged**
