### PR TITLE
typescript error default not defined

### PR DESCRIPTION
**Pull request by rayros**

### CODE REVIEW

**Comment by alexisvincent** [comment]
I think this is ok. @capaj can you confirm?

**Comment by alexisvincent** [comment]
@rayros did you test this? Because having another look it seems as if, not socketIO will be an object, and we rely on it being a function...

**Comment by rayros** [comment]
i test it on my project with angular2 and typescript, for angular2 i change typescript module to commonjs and i get error in socket.io-client i you want i can create simple project

**Comment by alexisvincent** [comment]
feel free to submit a PR containing a failing test case

**Comment by rayros** [comment]
btw. when will be new release?

**Pull request closed without merging**
